# Generated by Django 4.0 on 2022-03-31 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('share', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 31, 5, 53, 5, 868297))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 31, 5, 53, 5, 865498))),
                ('level', models.IntegerField(default=4)),
                ('answer_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('category', models.TextField()),
                ('level', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 31, 5, 53, 5, 867206))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=40)),
                ('level', models.IntegerField()),
                ('combination', models.CharField(max_length=3)),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 31, 5, 53, 5, 868297))),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.post')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
                ('zid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.user'),
        ),
        migrations.CreateModel(
            name='Question_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='usr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.user'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 31, 5, 53, 5, 868297))),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSuggested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_description', models.TextField()),
                ('q_answer', models.TextField()),
                ('q_options', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.user')),
            ],
        ),
    ]
