# Generated by Django 4.0.3 on 2022-04-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_alter_feedback_date_alter_notes_date_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 16, 10, 7, 550161)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 16, 10, 7, 550161)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 16, 10, 7, 534536)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 16, 10, 7, 534536)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 16, 10, 7, 534536)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 16, 10, 7, 550161)),
        ),
    ]
