# Generated by Django 4.0.4 on 2022-06-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0016_alter_feedback_date_alter_notes_date_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
        migrations.AlterField(
            model_name='replyreplies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 51, 29, 832637)),
        ),
    ]
