# Generated by Django 4.0.4 on 2022-06-27 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0018_quiz_qtype_alter_feedback_date_alter_notes_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
        migrations.AlterField(
            model_name='replyreplies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 17, 20, 18, 181316)),
        ),
    ]
