# Generated by Django 4.2 on 2023-04-21 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0019_post_reply_count_alter_feedback_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 891023)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 892034)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 889523)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 887492)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 889013)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 890511)),
        ),
        migrations.AlterField(
            model_name='replyreplies',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 7, 3, 892034)),
        ),
    ]
